import { Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";

import { dir } from "i18next";
import { languages } from "../i18n/settings";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Booking.com Clone",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html dir={dir(locale)}>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
